#!/usr/bin/env bash
set -eu -o pipefail

# Make sure the required image has been built
docker build -t aladdin-pre-push-secrets - < .githooks/lib/secrets-check.dockerfile >/dev/null

echo -n "Running trufflehog..."
docker run --rm -v "${PWD#/cygdrive}:/code" aladdin-pre-push-secrets \
    trufflehog --regex --entropy=False --exclude_paths .githooks/lib/trufflehog-excluded.txt .
echo " success"

echo -n "Running AWS git-secrets..."
docker run --rm -v "${PWD#/cygdrive}:/code" aladdin-pre-push-secrets \
    git secrets --scan-history
echo " success"
