name: "aladdin-values"
version: "0.1.0"
usage: "get values from aladdin"
description: "helm upgrade --install my-release path/to/my-chart -f aladdin://CLUSTER/my-repo?chart=my-chart&git-ref=main"
command: $HELM_PLUGIN_DIR/scripts/helm_plugin.sh
downloaders:
- command: scripts/helm_plugin.sh
  protocols:
  - "aladdin"
