#!/usr/bin/env bash
set -eu -o pipefail

export CLUSTER_COMMAND_PATH="$ALADDIN_DIR/aladdin/bash/container/cluster/cluster"
export S3_HELM_CHART_BUCKET=$(jq -r .publish.s3_helm_chart_bucket "$ALADDIN_CONFIG_DIR/config.json")
TEST_REMOTE_DIR=$(dirname $0)

function test_remote {
    bats "$TEST_REMOTE_DIR/test-cluster-create-config.bats"
    bats "$TEST_REMOTE_DIR/test-cluster-export-config.bats"
    bats "$TEST_REMOTE_DIR/test-cluster-import-config.bats"
    bats "$TEST_REMOTE_DIR/test-cluster-create-at-aws.bats"
    bats "$TEST_REMOTE_DIR/test-publish.bats"
    bats "$TEST_REMOTE_DIR/test-deploy.bats"
    bats "$TEST_REMOTE_DIR/test-rollback.bats"
    bats "$TEST_REMOTE_DIR/test-undeploy.bats"
    bats "$TEST_REMOTE_DIR/test-cluster-delete.bats"
}

function usage {
    cat <<-EOF
		usage: aladdin test-remote [-h]

		optional arguments:
		  -h, --help            show this help message and exit
	EOF
}

if [[ $# -eq 0 ]]; then
    if ! $IS_LOCAL && $IS_TESTING; then
        test_remote
    else
        echo >&2 "aladdin test-remote should only be called on a non local testing remote cluster"
    fi
elif [[ "$1" == "-h" || "$1" == "--help" ]]; then
    usage
else
    echo >&2 "aladdin: error: unrecognized arguments: $1"
    exit 1
fi
