#!/usr/bin/env bash
set -eu -o pipefail

function config() {
    local subcommand="$1"
    shift
    local config_dir="$HOME/.aladdin/config"
    local config_path="$HOME/.aladdin/config/config.json"
    if [ ! -f "$config_path" ]; then
        mkdir -p "$config_dir"
        echo '{}' > "$config_path"
    fi
    case "$subcommand" in
        get)
            default="${2:-}"
            result="$(jq -r --arg key "$1" 'getpath($key | split("."))' "$config_path")"
            if [[ ! "$result" == null ]]; then
                echo $result
            elif test -n "$default"; then
                echo $default
            fi
        ;;
        set)
            jq --arg key "$1" --arg val "$2" 'setpath($key | split("."); $val)' "$config_path" > "tmp.$$.json" && mv "tmp.$$.json" "$config_path"
        ;;
        view)
            cat "$config_path"
        ;;
        unset)
            jq --arg key "$1" 'delpaths([$key | split(".")])' "$config_path" > "tmp.$$.json" && mv "tmp.$$.json" "$config_path"
        ;;
        *)
            echo "unknown subcommand $subcommand for aladdin config command"
            exit 1
        ;;
    esac
}

function usage {
    cat <<-EOF
		usage: aladdin config [-h] SUBCOMMAND

		Available Subcommands:
		  get         Get the value of CONFIG_NAME
		  set         Set the value of CONFIG_NAME to CONFIG_VALUE
		  view        See all set configs
		  unset       Unset value of CONFIG_NAME

		optional arguments:
		  -h, --help            show this help message and exit
	EOF
}

if [[ $# -eq 0 || "$1" == "-h" ]]; then
    usage
else
    config "$@"
fi
