#!/usr/bin/env bash
set -eu -o pipefail

function helm_history {
    helm history $1-$NAMESPACE
}

function help {
    cat <<-EOF
		usage: aladdin helm-history [-h] project

		positional arguments:
		  project               the project whose history you want
          
		optional arguments:
		  -h, --help            show this help message and exit
	EOF
}

if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
    help
else
    helm_history "$1"
fi
