#!/usr/bin/env python3
import logging
from datetime import datetime


def get_hostedzone(boto_session, dns_name):
    log = logging.getLogger(__name__)
    route53 = boto_session.client('route53')

    zones = route53.list_hosted_zones_by_name(DNSName=dns_name)['HostedZones']

    # get only the public ones
    zones = [z for z in zones if not z['Config']['PrivateZone']
             and z['Name'].strip('.') == dns_name]

    if not zones:
        log.info('Hosted zone %s not found', dns_name)
        return None

    if len(zones) > 1:
        raise Exception('More than 1 hosted zone for %s' % dns_name)

    zone_id_res = zones[0]['Id']
    log.info('Hosted zone %s found : %s', dns_name, zone_id_res)
    return zone_id_res


def create_hostedzone(boto_session, dns_name):
    log = logging.getLogger(__name__)
    route53 = boto_session.client('route53')

    ref = 'aladdin_generated_{:%Y%m%d_%H%M%S}'.format(datetime.now())

    log.info('Hosted zone %s created', dns_name)

    log.info('Creating hosted zone : %s', dns_name)
    create_res = route53.create_hosted_zone(
        Name=dns_name,
        CallerReference=ref,
        HostedZoneConfig=dict(
            Comment='Generated by aladdin',
            PrivateZone=False,
        ),
    )

    id_res = create_res['HostedZone']['Id']

    return id_res


def get_ns_from_hostedzone(boto_session, dns_id):
    route53 = boto_session.client('route53')

    hosted_info = route53.get_hosted_zone(Id=dns_id)

    dns_name = hosted_info['HostedZone']['Name'].strip('.')

    response = route53.list_resource_record_sets(
        HostedZoneId=dns_id,
        StartRecordName=dns_name,
        StartRecordType='NS',
    )

    if response['IsTruncated']:
        raise Exception('Does not handle truncated hostedzone')

    rrs_list = [rrs for rrs in response['ResourceRecordSets'] if
                rrs['Name'] == '%s.' % dns_name and rrs['Type'] == 'NS']

    if len(rrs_list) == 0:
        raise Exception('Main NS in hosted zone not found')

    if len(rrs_list) > 1:
        raise Exception('Too much Main NS in hosted zone found')

    res = [rr['Value'] for rr in rrs_list[0]['ResourceRecords']]

    return res


def check_ns_values(boto_session, main_hosted_id, sub_dns, ns_values):
    log = logging.getLogger(__name__)
    route53 = boto_session.client('route53')

    response = route53.list_resource_record_sets(
        HostedZoneId=main_hosted_id,
        StartRecordName=sub_dns,
        StartRecordType='NS',
    )

    if response['IsTruncated']:
        raise Exception('Does not handle truncated hostedzone')

    rrs_list = [rrs for rrs in response['ResourceRecordSets'] if
                rrs['Name'] == '%s.' % sub_dns and rrs['Type'] == 'NS']

    values = None
    if rrs_list:
        values = [rr['Value'] for rr in rrs_list[0]['ResourceRecords']]

    if values == ns_values:
        # Good case
        log.info('NS value from %s to %s is good', main_hosted_id, sub_dns)
        return

    log.info('Setting NS value from %s to %s', main_hosted_id, sub_dns)
    route53.change_resource_record_sets(
        HostedZoneId=main_hosted_id,
        ChangeBatch=dict(
            Comment='generated by aladdin',
            Changes=[dict(
                Action='UPSERT',
                ResourceRecordSet=dict(
                    Name='%s.' % sub_dns,
                    Type='NS',
                    TTL=5 * 60,  # 5 min
                    ResourceRecords=[{'Value': v} for v in ns_values],
                ),
            )]
        ),
    )


def extract_cname_mapping(boto_session, dns_id):
    route53 = boto_session.client('route53')

    response = route53.list_resource_record_sets(HostedZoneId=dns_id)
    if response['IsTruncated']:
        raise Exception('Does not handle truncated hostedzone')

    res = {}
    for rrs in response['ResourceRecordSets']:
        name, type, records = rrs['Name'], rrs['Type'], rrs['ResourceRecords']
        if type != 'CNAME':
            continue
        # CNAME have only one value
        res[name.strip('.')] = records[0]['Value']

    return res


def generate_record(name, value):
    return dict(
        Action='UPSERT',
        ResourceRecordSet=dict(
            Name=name,
            Type='CNAME',
            TTL=5 * 60,
            ResourceRecords=[dict(Value=value)],
        )
    )


def fill_dns_dict(boto_session, dns_id, key_vals):
    log = logging.getLogger(__name__)
    route53 = boto_session.client('route53')

    cname_mapping = extract_cname_mapping(boto_session, dns_id)

    key_vals_cleaned = {k: v for k, v in key_vals.items() if v is not None}

    to_upsert = set(key_vals_cleaned.items()) - set(cname_mapping.items())
    log.info('%s CNAME present / %s service mapping / %s common / %s to upsert',
             len(cname_mapping),
             len(key_vals_cleaned),
             len(set(key_vals_cleaned) & set(cname_mapping)),
             len(to_upsert),
             )

    for name, val in sorted(to_upsert):
        log.info('%s => %s', name, val)

    records = [generate_record(name, val) for name, val in sorted(to_upsert)]

    if records:
        route53.change_resource_record_sets(
            HostedZoneId=dns_id,
            ChangeBatch=dict(
                Comment='generated by aladdin',
                Changes=records,
            ),
        )

    return len(records)
