{{- $templateValues := dig "aladdin" "templateValues" 0 .Values.AsMap }}
{{- $valuesYaml := toYaml .Values }}
{{- $values := .Values }}
{{- range untilStep 0 (int $templateValues) 1 }}
    {{- $valuesYaml = tpl $valuesYaml (dict "Values" $values "Chart" $.Chart) }}
    {{- $values = fromYaml $valuesYaml }}
{{- end }}
{{- $valuesYaml }}
