#!/usr/bin/env bash
set -eu -o pipefail

function delete_namespace {
    helm delete --purge $(helm list | awk '{print $1}' | grep -E "\-$1\b")
    kubectl delete namespace $1
}

function help {
    cat <<-EOF
		usage: aladdin delete-namespace [-h] namespace

		positional arguments:
		  namespace             the namespace you want to delete
          
		optional arguments:
		  -h, --help            show this help message and exit
	EOF
}

if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
    help
else
    delete_namespace "$1"
fi
