#!/usr/bin/env bash
set -eu -o pipefail

function delete_namespace {
    helm delete -n $1 $(helm list --short -n $1)
    kubectl delete namespace $1
}

function usage {
    cat <<-EOF
		usage: aladdin delete-namespace [-h] namespace

		positional arguments:
		  namespace             the namespace you want to delete
          
		optional arguments:
		  -h, --help            show this help message and exit
	EOF
}

if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
    usage
else
    delete_namespace "$1"
fi
