# This workflow is setup to run CI checks for aladdin
# At this time it only ensures the docker image is buildable
# In the future it could run linting, tests, etc
name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ECR_REGISTRY: 281649891004.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # QEMU is needed to support multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64, linux/arm64

      - uses: werf/actions/install@v2
        with:
          version: v2.34.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Configure aws credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::281649891004:role/github-actions
          aws-region: us-east-1
          output-credentials: true

      - name: Login to ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: werf build (ECR)
        run: |
          . $(werf ci-env github --as-file)
          werf export \
            --repo ${{ env.ECR_REGISTRY }}/aladdin-cache \
            --tag ${{ env.ECR_REGISTRY }}/aladdin:${{ github.sha }} \
            --tag ${{ env.FS_REGISTRY }}/aladdin:latest

      - name: werf build
        run: |
          . $(werf ci-env github --as-file)

          werf cr login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}

          werf build --repo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
