# This workflow is setup to run CI checks for aladdin
# At this time it only ensures the docker image is buildable
# In the future it could run linting, tests, etc
name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - uses: werf/actions/install@v2
        with:
          version: v2.14.0

      - name: Run script
        run: |
          . $(werf ci-env github --as-file)
          werf build
        env:
          WERF_DISABLE_AUTO_HOST_CLEANUP: "1"
