# This workflow is setup to build and publish aladdin to ECR
name: Push to ECR

on:
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'
      - '*.*.*.*'

env:
  ECR_REGISTRY: public.ecr.aws/fivestars/aladdin

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # QEMU is needed to support multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64, linux/arm64

      - uses: werf/actions/install@v2
        with:
          version: v2.47.3

      # this will select the right tags depending on the Github event
      # master branch will build the "latest" and "main" Dockerhub tags
      # git tags will build the Dockerhub tag matching the git tag
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ECR_REGISTRY }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Configure aws credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::281649891004:role/public-github-actions
          aws-region: us-east-1
          output-credentials: true

      - name: Login to ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: werf publish
        run: |
          . $(werf ci-env github --as-file)

          werf export \
            --repo ${{ env.ECR_REGISTRY }} \
            --tag ${{ env.ECR_REGISTRY }}:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}


  cleanup:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Configure aws credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::281649891004:role/public-github-actions
          aws-region: us-east-1
          output-credentials: true

      - name: Login to ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - uses: werf/actions/install@v2
        with:
          version: v2.47.3

      - run: |
          . $(werf ci-env github --as-file)

          werf cleanup \
            --repo "${{ env.ECR_REGISTRY }}" \
            --without-kube=true
